cache-lifetime: 604800000 # 7 Days
kick-reason: "ACCESS DENIED"
deny-hostings: false
force-check: false
force-kick-reason: "Please, wait..."
timeout: 15000 # 15 Seconds
result-await: 1500 # 1.5 Seconds