cache-lifetime: 604800000 # 7 Days
mem-cache-expire: 10 # 10 Minutes
kick-reason: "ACCESS DENIED"
deny-hostings: false
force-check: false
force-kick-reason: "Please, wait..."
timeout: 15000 # 15 Seconds
result-await: 5 # 5 Milliseconds